re-remove rails things
saml-idp/saml_idp pull request #192
Opened 2023-05-02 21:42 UTC by jphenow

Does this about cover it @Zogoo?

2023-05-18 02:10 UTC, mjobin-mdsol requested changes
I think its good to keep this boilerplate for false start.
it does not cause any slowdown except for consuming a few bytes for those who don't need it.

2023-05-26 10:04 UTC, Zogoo commented
@mjobin-mdsol idea of removing rails-related things is to avoid having questions on the issues like how to override methods for this controller etc.

2023-05-26 10:04 UTC, Zogoo approved these changes

2023-05-28 20:28 UTC, Zogoo commented
@mjobin-mdsol if you still want to put back the rails app let's discuss over the issue meanwhile let me merge this PR because this was removed before.

2023-05-28 20:28 UTC, merged